spring.application.name=API-Gateway

server.port=8080

# ===== Telling the Gateway to search the Service registry for the Service name =====
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# ===== Used to register the service in the Service registry i.e Eureka server =====
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# ===== Explicit Auth Service Route =====
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTHSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# ===== Jwt secret =====
jwt.secret=wVr1EXS1pvvnzpoT12EAx6J1otxYrlKfkSb0Q+ksxcI=