spring.application.name=PaymentService

server.port=8085

spring.datasource.url=jdbc:postgresql://localhost:5432/PaymentService_db
spring.datasource.username=postgres
spring.datasource.password=jathin@10
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== Used to register the service in the Service registry i.e Eureka server =====
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.jpa.hibernate.ddl-auto=update