spring.application.name=AuthService

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/AuthService_db
spring.datasource.username=postgres
spring.datasource.password=jathin@10
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

# ===== Used to register the service in the Service registry i.e Eureka server =====
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
logging.level.org.springframework.security=DEBUG

# ===== Jwt secret =====
jwt.secret=wVr1EXS1pvvnzpoT12EAx6J1otxYrlKfkSb0Q+ksxcI=